### PR TITLE
Get the CI

### PR DESCRIPTION
**Pull request by xiki-tempula**

### CODE REVIEW

**Comment by xiki-tempula** [comment]
@selimsami Would you mind checking if additional steps need to be taken to enable the github actions and code convergence? I think these files should be enough to kick start the CI but it doesn't seem to me that the CI is triggered.

**Comment by selimsami** [comment]
@xiki-tempula, I don't have much experience with CI but I'll read up on it and test when I get a chance. Thanks for starting this up!

**Comment by selimsami** [comment]
Seems to work fine actually. Now gotta fix that awful coverage :-D

**Comment by xiki-tempula** [comment]
@selimsami Would you mind enable the codecov to access the github? So I could check if various functions of the codecov could be used.

**Comment by selimsami** [comment]
https://app.codecov.io/gh/selimsami/qforce

It has access, no?

**Pull request merged**
