### PR TITLE
Add the test to test if LP is read correctly

### PR DESCRIPTION
**Pull request by xiki-tempula**
Based on the test set https://github.com/selimsami/qforce_examples/pull/3

### CODE REVIEW

**Comment by selimsami** [comment]
CI seems to fail for this PR?

**Comment by xiki-tempula** [comment]
@selimsami The PR need new examples from the https://github.com/selimsami/qforce_examples/pull/3

**Comment by selimsami** [comment]
@xiki-tempula , something still seems wrong?

**Comment by xiki-tempula** [comment]
@selimsami The issues should be fixed now. I made an error when resolving the conflict.

**Comment by xiki-tempula** [comment]
@selimsami Do you mind doing a pip release after this PR is merged? Like 0.7.0? Thank you.

**Pull request merged**
