### PR TITLE
update gaff.itp gaff2.itp

### PR DESCRIPTION
**Pull request by xiki-tempula**
I have added the atomic number to the two itp. This fixed the #20.

### CODE REVIEW

**Comment by selimsami** [comment]
From a quick look, in gaff.itp it looks like the LJ parameters have changed. (f.e. atom type: ca)

**Comment by xiki-tempula** [comment]
I think this is probably because I'm using a newer version of the gaff (Version 1.81, May 2017), which is the latest version from ambertools. I wonder where did you obtain this gaff.itp?

**Comment by selimsami** [comment]
Can't really remember unfortunately. But it's best to use the most up-to-date version I assume. 

I see that you obtained them with parmed, but do you have a reference/citation for these parameters? Just to avoid similar problems in the future.

**Comment by xiki-tempula** [comment]
So parmed is a conversion package that parses the amber topology file and is part of the ambertools (so I don't need to write a script to read amber topology). Citation: https://dx.doi.org/10.1007/s10822-016-9977-1
So I install the amber tools with conda.
Then I use parmed to read the corresponding gaff.dat and gaff2.dat from the amber tools installation and write it to the itp files.
The exact code to generate the files is in the header of the itp file.

**Comment by selimsami** [comment]
Great, then I consider this issue resolved. Thanks for the new parameters!

**Pull request merged**
