### PR TITLE
fix codecov

### PR DESCRIPTION
**Pull request by xiki-tempula**
Trying to fix codecov

### CODE REVIEW

**Comment by xiki-tempula** [comment]
@selimsami Sorry, I have opened this PR trying to diagnose the problem. I haven't fixed the problem yet.

**Comment by selimsami** [comment]
Oh... what is the problem?

**Comment by xiki-tempula** [comment]
@selimsami You might notice that the codecov has gone to 0%. So I was trying to figure out why it is 0%.

**Comment by selimsami** [comment]
hmm I hope I didn't mess something up. I noticed that the codecov webhook was not working on github, so I removed it. but reauthenticating codecov did not add the webhook back.

Let me know if you think it's a permission problem and I'll have another look.

But it does look like it still has access...

**Comment by xiki-tempula** [comment]
@selimsami I guess we can wait for a day to see if it got fixed by itself.

**Comment by selimsami** [comment]
@xiki-tempula , does this help?

https://codecov.io/api/gh/selimsami/qforce/download/build?path=v4/raw/2021-12-09/C6EAE6A8CDB9E671E31BF66F1F32E481/3142e362f63093766292cda085adee90a9f07cdd/82f5e153-206d-414e-91f7-d81c6ba92936.txt

**Comment by selimsami** [comment]
and  this : 

https://justpaste.it/48h1n

**Comment by xiki-tempula** [comment]
@selimsami Ok, I think this is a problem on your end. I have copied the whole repo to my account and tested it and it seems that with the same config file, the codecov works correctly. 
You might wish to contact codecov to see if they are willing to help?

**Comment by selimsami** [comment]
@xiki-tempula thanks for this.
Could you perhaps go to settings>webhooks on your repository and tell me know (or share a screengrab) of the settings for codecov?
Perhaps adding it back manually would help

**Pull request merged**
